[package]
name = "funciones"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.104"
web-sys = { version = "0.3.81", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.54"

[profile.release]
opt-level = "s"